version: "3.1"

intents:
  - saludo
  - despedida
  - afirmar
  - negar
  - estado_genial
  - estado_triste
  - desafio_bot
  - out_of_scope
  - fallback
  - asistencia_tecnica
  - informar_git

responses:
  utter_saludo:
  - text: "¡Hola! ¿Cómo estás?"

  utter_cheer_up:
  - text: "Espero que te sientas mejor pronto."

  utter_did_that_help:
  - text: "¿Te ayudó eso?"

  utter_despedida:
  - text: "Adiós"

  utter_yosoyunbot:
  - text: "Soy un bot, impulsado por Rasa."

  utter_out_of_scope:
  - text: "Lo siento, no puedo ayudarte con eso. ¿Quieres saber algo sobre Rasa?"

  utter_fallback:
  - text: "No entendí tu mensaje. ¿Puedes reformularlo o preguntar sobre Rasa?"

  utter_ofrecer_ayuda:
  - text: "Bien, ¿En qué te puedo ayudar? ¿Asistencia técnica para Instalar Rasa? ¿Capacitaciones sobre este tema?"

  utter_asistencia_tecnica:
  - text: "¡Perfecto! Te puedo guiar para instalar Rasa en tu PC."

  utter_ask_git_instalado:
  - text: "¿Tienes Git instalado en tu sistema?"

  utter_confirmar_git:
  - text: "Gracias por la información sobre Git. Ahora podemos continuar con la instalación de Rasa."

  utter_ask_proyecto_descargado:
  - text: "¿Ya tienes descargado el proyecto messenger-bridge de GitHub?"

  utter_guia_clonar_proyecto:
  - text: "Vamos a descargar el proyecto usando Git. Ejecuta el siguiente comando en tu terminal: git clone https://github.com/AgustinMadygraf/messenger-bridge"

actions:
  - validate_instalar_rasa_form

session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true

slots:
  git_instalado:
    type: text
    influence_conversation: true
    mappings:
      - type: from_text
        conditions:
          - active_loop: instalar_rasa_form
            requested_slot: git_instalado

  proyecto_descargado:
    type: text
    influence_conversation: true
    mappings:
      - type: from_text
        conditions:
          - active_loop: instalar_rasa_form
            requested_slot: proyecto_descargado

forms:
  instalar_rasa_form:
    required_slots:
      - proyecto_descargado
      - git_instalado
